<?php

/**
 * @file
 * Contains image_lightgallery_formatter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function image_lightgallery_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the image_lightgallery_formatter module.
    case 'help.page.image_lightgallery_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('An image field formatter based on jquery lightgallery library') . '</p>';
      return $output;

    default:
  }
}
